### ISSUE TITLE
rule_id's should not be assigned from the comment field

### ISSUE THREAD

**Issue by ftyers** [sevilaybayatli/apertium-ambiguous#13]
The description/name of the rule should be in a separate attribute, it should not be parsed from the comment field.

```
      // name of the file is the concatenation of rules ids
      string rulesNums;
      for (unsigned x = 0; x < ambigRules.size (); x++)
	{
	  for (unsigned y = 0; y < ambigRules[x].size (); y++)
	    {
	      xml_node rule = ambigRules[x][y];
	      string ruleCmnt = rule.first_attribute ().value ();

	      rulesNums += ruleCmnt.substr (ruleCmnt.find_last_of ("-") + 1);
	      rulesNums += "_";

	    }
	  rulesNums += "+";
	}
```

One possibility would be to use a simple "id" attribute, as in [here](https://svn.code.sf.net/p/apertium/svn/branches/weighted-transfer/apertium-toy-ru-en/apertium-rus-eng/apertium-rus-eng.rus-eng.t1x).

**Comment by sevilaybayatli** [comment]
this fixed  like <rule id="78" comment="REGLA: cop-ger-past">

// name of the file is the concatenation of rules ids
      string rulesNums;
      for (unsigned x = 0; x < ambigRules.size (); x++)
	{
	  for (unsigned y = 0; y < ambigRules[x].size (); y++)
	    {
	      xml_node rule = ambigRules[x][y];
	      string ruleId = rule.first_attribute ().value ();

	      rulesNums += ruleId.substr (ruleId.find_last_of ("") + 1);
	      rulesNums += "_";

	    }
	  rulesNums += "+";
	}

**Comment by ftyers** [comment]
Are you use `first_attribute()` is the right method to call ? 

How about if you had a rule like:

```xml
<rule comment="REGLA: cop-ger-past"  id="78">
```
